/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.AlunoController;
import controller.UsuarioController;
import controller.tpMovimentacaoController;
import controller.tpPagamentoController;
import ferramentas.CaixaDeDialogo;
import static groovy.sql.Sql.resultSet;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author lucas.pandolfo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeUsu_principal = new javax.swing.JLabel();
        txtNomeUsuario_principal = new javax.swing.JLabel();
        lblReceitaMes_principal = new javax.swing.JLabel();
        txtReceitaTotal_principal = new javax.swing.JLabel();
        txtReceitaMes_principal = new javax.swing.JLabel();
        lblReceitaTota_principal = new javax.swing.JLabel();
        lblDespesaTota_principal = new javax.swing.JLabel();
        txtDespesaMes_principal = new javax.swing.JLabel();
        txtDespesaTotal_principal = new javax.swing.JLabel();
        lblDespesaMes_principal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAlunos = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuTpPagamento = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        parametrosRe = new javax.swing.JMenuItem();
        ReUsuarioCompleto = new javax.swing.JMenuItem();
        ReTipoPagamento = new javax.swing.JMenuItem();
        ReTipoMovimentacao = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        lblNomeUsu_principal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeUsu_principal.setText("Nome do Usuário:");

        lblReceitaMes_principal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReceitaMes_principal.setText("Valor Receita Mes:");

        txtReceitaTotal_principal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblReceitaTota_principal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReceitaTota_principal.setText("Valor Receita Total:");

        lblDespesaTota_principal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDespesaTota_principal.setText("Valor Despesa Total:");

        lblDespesaMes_principal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDespesaMes_principal.setText("Valor Despesa Mes:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadasro.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        menuAlunos.setText("Alunos");
        menuAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(menuAlunos);

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usuario.png"))); // NOI18N
        menuUsuarios.setText("Usuaros");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuarios);

        menuTpPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tpPag.png"))); // NOI18N
        menuTpPagamento.setText("Tipo de Pagamento");
        menuTpPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTpPagamentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuTpPagamento);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tpMovi.png"))); // NOI18N
        jMenuItem1.setText("Tipo de Movimentação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatório.png"))); // NOI18N
        jMenu2.setText("Relatórios");

        parametrosRe.setText("Parametos de Relatório");
        parametrosRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametrosReActionPerformed(evt);
            }
        });
        jMenu2.add(parametrosRe);

        ReUsuarioCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatório.png"))); // NOI18N
        ReUsuarioCompleto.setText("Relatório Completo Usuarios");
        ReUsuarioCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReUsuarioCompletoActionPerformed(evt);
            }
        });
        jMenu2.add(ReUsuarioCompleto);

        ReTipoPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatório.png"))); // NOI18N
        ReTipoPagamento.setText("Relatório Completo Tipo Pagamento");
        ReTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReTipoPagamentoActionPerformed(evt);
            }
        });
        jMenu2.add(ReTipoPagamento);

        ReTipoMovimentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatório.png"))); // NOI18N
        ReTipoMovimentacao.setText("Relatório Completo Tipo Movimentação ");
        ReTipoMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReTipoMovimentacaoActionPerformed(evt);
            }
        });
        jMenu2.add(ReTipoMovimentacao);

        jMenuBar1.add(jMenu2);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        jMenuItem2.setText("Sair do Sistema");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem2);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDespesaTota_principal)
                            .addComponent(lblDespesaMes_principal))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDespesaMes_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDespesaTotal_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeUsu_principal)
                                    .addComponent(lblReceitaMes_principal))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeUsuario_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReceitaMes_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReceitaTota_principal)
                                .addGap(36, 36, 36)
                                .addComponent(txtReceitaTotal_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeUsuario_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeUsu_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReceitaMes_principal)
                            .addComponent(txtReceitaMes_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReceitaTota_principal)
                            .addComponent(txtReceitaTotal_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDespesaTota_principal)
                    .addComponent(txtDespesaTotal_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDespesaMes_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDespesaMes_principal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuTpPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTpPagamentoActionPerformed
        // TODO add your handling code here:
        TipoPagamentoView TpPagamento = new TipoPagamentoView();
        TpPagamento.setVisible(true);
        
    }//GEN-LAST:event_menuTpPagamentoActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        // TODO add your handling code here:
        UsuariosView usuarios = new UsuariosView();
        usuarios.setVisible(true);
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TipoMovimentacaoView tipomovi = new TipoMovimentacaoView();
        tipomovi.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       System.exit(0);        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlunosActionPerformed
        // TODO add your handling code here:
        AlunosView alunos = new AlunosView();
        alunos.setVisible(true);
    }//GEN-LAST:event_menuAlunosActionPerformed

    private void ReUsuarioCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReUsuarioCompletoActionPerformed
        // TODO add your handling code here:
        
         // metodo para gerar um relaório
         
         // Para criar o arquivo .jasper na pasa tem que cicar em preview no iReport
       
      
        try {
            
            UsuarioController objUsuaioCon = new UsuarioController(null, null);
            ResultSet resultSet = objUsuaioCon.buscarRelatorio();//Buscar os dados do relatório
            JRResultSetDataSource relResult = new JRResultSetDataSource(resultSet);//Passa um resultSet para a fonte de dados do relatório
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/usuariosCompleto.jasper", new HashMap(), relResult);//Prepara o relatório para ser impresso, recebe o gerenciador JASPER
            JasperViewer jpViewer = new JasperViewer(jpPrint, false); //
            jpViewer.setVisible(true);//abre o relatório para visualização
            jpViewer.toFront();//define o form a frente da aplicação
            
        } catch (JRException ex) {
            
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
        
            
        
        
        
    }//GEN-LAST:event_ReUsuarioCompletoActionPerformed

    private void ReTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReTipoPagamentoActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        
         // metodo para gerar um relaório
         
         // Para criar o arquivo .jasper na pasa tem que cicar em preview no iReport
       
      
        try {
            
            tpPagamentoController objtppagCon = new tpPagamentoController(null, null);
            ResultSet resultSet = objtppagCon.buscarRelatorio();//Buscar os dados do relatório
            JRResultSetDataSource relResult = new JRResultSetDataSource(resultSet);//Passa um resultSet para a fonte de dados do relatório
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/tipoPagamento.jasper", new HashMap(), relResult);//Prepara o relatório para ser impresso, recebe o gerenciador JASPER
            JasperViewer jpViewer = new JasperViewer(jpPrint, false); //
            jpViewer.setVisible(true);//abre o relatório para visualização
            jpViewer.toFront();//define o form a frente da aplicação
            
        } catch (JRException ex) {
            
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_ReTipoPagamentoActionPerformed

    private void ReTipoMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReTipoMovimentacaoActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        
         // metodo para gerar um relaório
         
         // Para criar o arquivo .jasper na pasa tem que cicar em preview no iReport
       
      
        try {
            
            tpMovimentacaoController objtpmovi = new tpMovimentacaoController(null, null);
            ResultSet resultSet = objtpmovi.buscarRelatorio();//Buscar os dados do relatório
            JRResultSetDataSource relResult = new JRResultSetDataSource(resultSet);//Passa um resultSet para a fonte de dados do relatório
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/tipoMovimentacao.jasper", new HashMap(), relResult);//Prepara o relatório para ser impresso, recebe o gerenciador JASPER
            JasperViewer jpViewer = new JasperViewer(jpPrint, false); //
            jpViewer.setVisible(true);//abre o relatório para visualização
            jpViewer.toFront();//define o form a frente da aplicação
            
        } catch (JRException ex) {
            
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
        
        
    }//GEN-LAST:event_ReTipoMovimentacaoActionPerformed

    private void parametrosReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametrosReActionPerformed
        // TODO add your handling code here:
        ParametrosRelatoriosView parametros = new ParametrosRelatoriosView();
        parametros.setVisible(true);
    }//GEN-LAST:event_parametrosReActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ReTipoMovimentacao;
    private javax.swing.JMenuItem ReTipoPagamento;
    private javax.swing.JMenuItem ReUsuarioCompleto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDespesaMes_principal;
    private javax.swing.JLabel lblDespesaTota_principal;
    private javax.swing.JLabel lblNomeUsu_principal;
    private javax.swing.JLabel lblReceitaMes_principal;
    private javax.swing.JLabel lblReceitaTota_principal;
    private javax.swing.JMenuItem menuAlunos;
    private javax.swing.JMenuItem menuTpPagamento;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenuItem parametrosRe;
    private javax.swing.JLabel txtDespesaMes_principal;
    private javax.swing.JLabel txtDespesaTotal_principal;
    private javax.swing.JLabel txtNomeUsuario_principal;
    private javax.swing.JLabel txtReceitaMes_principal;
    private javax.swing.JLabel txtReceitaTotal_principal;
    // End of variables declaration//GEN-END:variables
}
